export default {
  sidebar: {
    '/tool/': [
      {
        text: 'GIT',
        items: [
          { text: 'git', link: '/tool/git/README.html' }
        ]
      }, {
        text: 'Linux',
        items: [
          { text: 'linux', link: '/tool/linux/README.html' }
        ]
      }],
    '/AI/': [{
      text: "Claude Code 文档", collapsed: false, items: [
        { text: '📚 文档导航', link: '/AI/README.html' },
        { text: '🎯 快速上手教程', link: '/AI/快速上手教程.html' },
        { text: '📖 提示词模板库', link: '/AI/ClaudeCode.html' },
        { text: '🚀 实战指南', link: '/AI/实战指南.html' },
        { text: '⚡ 进阶技巧', link: '/AI/进阶技巧.html' },
      ]
    }],
    "/database/sakila/": [
      { text: "安装 Sakila 数据库", link: '/database/sakila/index.html' },
      {
        text: "Sakila 数据库结构", items: [
          { text: '演员表', link: '/database/sakila/演员表.html' },
          { text: '地址表', link: '/database/sakila/地址表.html' },
          { text: '类别表', link: '/database/sakila/类别表.html' },
          { text: '城市表', link: '/database/sakila/城市表.html' },
          { text: '国家表', link: '/database/sakila/国家表.html' },
          { text: '客户表', link: '/database/sakila/客户表.html' },
          { text: '影片演员关系表', link: '/database/sakila/影片演员关系表.html' },
          { text: '影片类别关系表', link: '/database/sakila/影片类别关系表.html' },
          { text: '影片描述表', link: '/database/sakila/影片描述表.html' },
          { text: '影片表', link: '/database/sakila/影片表.html' },
          { text: '库存表', link: '/database/sakila/库存表.html' },
          { text: '语言表', link: '/database/sakila/语言表.html' },
          { text: '支付表', link: '/database/sakila/支付表.html' },
          { text: '租赁表', link: '/database/sakila/租赁表.html' },
          { text: '员工表', link: '/database/sakila/员工表.html' },
          { text: '商店表', link: '/database/sakila/商店表.html' },
          { text: '视图', link: '/database/sakila/视图.html' },
          { text: '存储过程', link: '/database/sakila/存储过程.html' },
          { text: '存储函数', link: '/database/sakila/存储函数.html' },
          { text: '触发器', link: '/database/sakila/触发器.html' },
        ]
      },
    ],
    "/database/postgreSQL/ref/": [
      {
        text: "PostgreSQL 字符串函数", collapsed: true, items: [
          { text: 'ascii', link: '/database/postgreSQL/ref/ascii.html' },
          { text: 'trim', link: '/database/postgreSQL/ref/trim.html' },
          { text: 'ltrim', link: '/database/postgreSQL/ref/ltrim.html' },
          { text: 'rtrim', link: '/database/postgreSQL/ref/rtrim.html' },
          { text: 'btrim', link: '/database/postgreSQL/ref/btrim.html' },
          { text: 'length', link: '/database/postgreSQL/ref/length.html' },
          { text: 'char_length', link: '/database/postgreSQL/ref/char_length.html' },
          { text: 'character_length', link: '/database/postgreSQL/ref/character_length.html' },
          { text: 'octet_length', link: '/database/postgreSQL/ref/octet_length.html' },
          { text: 'bit_length', link: '/database/postgreSQL/ref/bit_length.html' },
          { text: 'concat', link: '/database/postgreSQL/ref/concat.html' },
          { text: 'concat_ws', link: '/database/postgreSQL/ref/concat_ws.html' },
          { text: 'format', link: '/database/postgreSQL/ref/format.html' },
          { text: 'initcap', link: '/database/postgreSQL/ref/initcap.html' },
          { text: 'left', link: '/database/postgreSQL/ref/left.html' },
          { text: 'right', link: '/database/postgreSQL/ref/right.html' },
          { text: 'lower', link: '/database/postgreSQL/ref/lower.html' },
          { text: 'upper', link: '/database/postgreSQL/ref/upper.html' },
          { text: 'lpad', link: '/database/postgreSQL/ref/lpad.html' },
          { text: 'rpad', link: '/database/postgreSQL/ref/rpad.html' },
          { text: 'md5', link: '/database/postgreSQL/ref/md5.html' },
          { text: 'normalize', link: '/database/postgreSQL/ref/normalize.html' },
          { text: 'overlay', link: '/database/postgreSQL/ref/overlay.html' },
          { text: 'parse_ident', link: '/database/postgreSQL/ref/parse_ident.html' },
          { text: 'pg_client_encoding', link: '/database/postgreSQL/ref/pg_client_encoding.html' },
          { text: 'position', link: '/database/postgreSQL/ref/position.html' },
          { text: 'strpos', link: '/database/postgreSQL/ref/strpos.html' },
          { text: 'quote_ident', link: '/database/postgreSQL/ref/quote_ident.html' },
          { text: 'quote_literal', link: '/database/postgreSQL/ref/quote_literal.html' },
          { text: 'quote_nullable', link: '/database/postgreSQL/ref/quote_nullable.html' },
          { text: 'regexp_match', link: '/database/postgreSQL/ref/regexp_match.html' },
          { text: 'regexp_matches', link: '/database/postgreSQL/ref/regexp_matches.html' },
          { text: 'regexp_replace', link: '/database/postgreSQL/ref/regexp_replace.html' },
          { text: 'regexp_split_to_array', link: '/database/postgreSQL/ref/regexp_split_to_array.html' },
          { text: 'regexp_split_to_table', link: '/database/postgreSQL/ref/regexp_split_to_table.html' },
          { text: 'split_part', link: '/database/postgreSQL/ref/split_part.html' },
          { text: 'starts_with', link: '/database/postgreSQL/ref/starts_with.html' },
          { text: 'string_to_array', link: '/database/postgreSQL/ref/string_to_array.html' },
          { text: 'string_to_table', link: '/database/postgreSQL/ref/string_to_table.html' },
          { text: 'substr', link: '/database/postgreSQL/ref/substr.html' },
          { text: 'substring', link: '/database/postgreSQL/ref/substring.html' },
          { text: 'to_ascii', link: '/database/postgreSQL/ref/to_ascii.html' },
          { text: 'to_char', link: '/database/postgreSQL/ref/to_char.html' },
          { text: 'to_hex', link: '/database/postgreSQL/ref/to_hex.html' },
          { text: 'to_number', link: '/database/postgreSQL/ref/to_number.html' },
          { text: 'translate', link: '/database/postgreSQL/ref/translate.html' },
          { text: 'unistr', link: '/database/postgreSQL/ref/unistr.html' },
        ]
      },
      {
        text: "PostgreSQL 数学函数", collapsed: true, items: [
          { text: 'abs绝对值', link: '/database/postgreSQL/ref/abs.html' },
          { text: 'acos反余弦值弧度', link: '/database/postgreSQL/ref/acos.html' },
          { text: 'acosd反余弦值度', link: '/database/postgreSQL/ref/acosd.html' },
          { text: 'acosh反双曲余弦', link: '/database/postgreSQL/ref/acosh.html' },
          { text: 'asin反正弦弧度', link: '/database/postgreSQL/ref/asin.html' },
          { text: 'asind反正弦度', link: '/database/postgreSQL/ref/asind.html' },
          { text: 'asinh反双曲正弦', link: '/database/postgreSQL/ref/asinh.html' },
          { text: 'atan反正切弧度', link: '/database/postgreSQL/ref/atan.html' },
          { text: 'atand反正切度', link: '/database/postgreSQL/ref/atand.html' },
          { text: 'atan2反正切弧度', link: '/database/postgreSQL/ref/atan2.html' },
          { text: 'atan2d反正切度', link: '/database/postgreSQL/ref/atan2d.html' },
          { text: 'atanh反双曲正切', link: '/database/postgreSQL/ref/atanh.html' },
          { text: 'cbrt立方根', link: '/database/postgreSQL/ref/cbrt.html' },
          { text: 'ceil向上取整', link: '/database/postgreSQL/ref/ceil.html' },
          { text: 'ceiling向上取整', link: '/database/postgreSQL/ref/ceiling.html' },
          { text: 'cos余弦值弧度', link: '/database/postgreSQL/ref/cos.html' },
          { text: 'cosd余弦值度', link: '/database/postgreSQL/ref/cosd.html' },
          { text: 'cosh双曲余弦', link: '/database/postgreSQL/ref/cosh.html' },
          { text: 'cot余切弧度', link: '/database/postgreSQL/ref/cot.html' },
          { text: 'cotd余切度', link: '/database/postgreSQL/ref/cotd.html' },
          { text: 'degrees弧度值转度数值', link: '/database/postgreSQL/ref/degrees.html' },
          { text: 'div除法取商', link: '/database/postgreSQL/ref/div.html' },
          { text: 'mod除法取余数', link: '/database/postgreSQL/ref/mod.html' },
          { text: 'exp自然常数e的次方', link: '/database/postgreSQL/ref/exp.html' },
          { text: 'factorial阶乘', link: '/database/postgreSQL/ref/factorial.html' },
          { text: 'floor向下取整', link: '/database/postgreSQL/ref/floor.html' },
          { text: 'gcd最大公约数', link: '/database/postgreSQL/ref/gcd.html' },
          { text: 'icm最小公倍数', link: '/database/postgreSQL/ref/icm.html' },
          { text: 'ln自然对数', link: '/database/postgreSQL/ref/ln.html' },
          { text: 'log底的对数', link: '/database/postgreSQL/ref/log.html' },
          { text: 'log10以10为底的对数', link: '/database/postgreSQL/ref/log10.html' },
          { text: 'min_scale最小的精度', link: '/database/postgreSQL/ref/min_scale.html' },
          { text: 'pi圆周率 π 的近似值', link: '/database/postgreSQL/ref/pi.html' },
          { text: 'power指定数字的次方', link: '/database/postgreSQL/ref/power.html' },
          { text: 'radians度数值转为弧度值', link: '/database/postgreSQL/ref/radians.html' },
          { text: 'random随机数', link: '/database/postgreSQL/ref/random.html' },
          { text: 'round四舍五入', link: '/database/postgreSQL/ref/round.html' },
          { text: 'scale最小的小数位数', link: '/database/postgreSQL/ref/scale.html' },
          { text: 'setseed设置随积种子', link: '/database/postgreSQL/ref/setseed.html' },
          { text: 'sign数字的符号', link: '/database/postgreSQL/ref/sign.html' },
          { text: 'sin弧度的正弦值', link: '/database/postgreSQL/ref/sin.html' },
          { text: 'sind度的正弦值', link: '/database/postgreSQL/ref/sind.html' },
          { text: 'sinh双曲正弦', link: '/database/postgreSQL/ref/sinh.html' },
          { text: 'sind度的正弦值', link: '/database/postgreSQL/ref/sind.html' },
          { text: 'sqrt平方根', link: '/database/postgreSQL/ref/sqrt.html' },
          { text: 'tan弧度的正切', link: '/database/postgreSQL/ref/tan.html' },
          { text: 'tand度的正切', link: '/database/postgreSQL/ref/tand.html' },
          { text: 'tanh双曲正切', link: '/database/postgreSQL/ref/tanh.html' },
          { text: 'trim_scale去除小数结尾的0', link: '/database/postgreSQL/ref/trim_scale.html' },
          { text: 'trunc截断到指定的精度', link: '/database/postgreSQL/ref/trunc.html' },
          { text: 'width_bucket桶中的位置', link: '/database/postgreSQL/ref/width_bucket.html' },
        ]
      },
      {
        text: "PostgreSQL 时间函数", collapsed: true, items: [
          { text: 'age获取年龄', link: '/database/postgreSQL/ref/age.html' },
          { text: 'clock_timestamp当前日期和时间', link: '/database/postgreSQL/ref/clock_timestamp.html' },
          { text: 'current_date当前日期', link: '/database/postgreSQL/ref/current_date.html' },
          { text: 'current_time当前时间', link: '/database/postgreSQL/ref/current_time.html' },
          { text: 'current_timestamp当前日期和时间', link: '/database/postgreSQL/ref/current_timestamp.html' },
          { text: 'date_bin时间间隔的开始', link: '/database/postgreSQL/ref/date_bin.html' },
          { text: 'date_part间隔值', link: '/database/postgreSQL/ref/date_part.html' },
          { text: 'date_trunc间隔类型', link: '/database/postgreSQL/ref/date_trunc.html' },
          { text: 'extract时间间隔中抽取', link: '/database/postgreSQL/ref/extract.html' },
          { text: 'isfinite间隔值是否是有限大', link: '/database/postgreSQL/ref/isfinite.html' },
          { text: 'justify_days天数转为月数', link: '/database/postgreSQL/ref/justify_days.html' },
          { text: 'justify_hours小时数转为天数', link: '/database/postgreSQL/ref/justify_hours.html' },
          { text: 'justify_interval小时转天,天转月', link: '/database/postgreSQL/ref/justify_interval.html' },
          { text: 'localtime系统时间', link: '/database/postgreSQL/ref/localtime.html' },
          { text: 'localtimestamp系统日期时间', link: '/database/postgreSQL/ref/localtimestamp.html' },
          { text: 'make_date日期值', link: '/database/postgreSQL/ref/make_date.html' },
          { text: 'make_interval间隔值', link: '/database/postgreSQL/ref/make_interval.html' },
          { text: 'make_time时间值', link: '/database/postgreSQL/ref/make_time.html' },
          { text: 'make_timestamp时间戳值', link: '/database/postgreSQL/ref/make_timestamp.html' },
          { text: 'make_timestamptz时间戳值(时区)', link: '/database/postgreSQL/ref/make_timestamptz.html' },
          { text: 'now当前日期时间', link: '/database/postgreSQL/ref/now.html' },
          { text: 'pg_sleep睡眠(秒)', link: '/database/postgreSQL/ref/pg_sleep.html' },
          { text: 'pg_sleep_for睡眠', link: '/database/postgreSQL/ref/pg_sleep_for.html' },
          { text: 'pg_sleep_until睡眠(时刻)', link: '/database/postgreSQL/ref/pg_sleep_until.html' },
          { text: 'statement_timestamp语句开始执行时间', link: '/database/postgreSQL/ref/statement_timestamp.html' },
          { text: 'timeofday时间戳的字符串', link: '/database/postgreSQL/ref/timeofday.html' },
          { text: 'to_date字符串转日期', link: '/database/postgreSQL/ref/to_date.html' },
          { text: 'to_timestamp字符串转时间', link: '/database/postgreSQL/ref/to_timestamp.html' },
          { text: 'transaction_timestamp当前日期时间', link: '/database/postgreSQL/ref/transaction_timestamp.html' },
        ]
      },
      {
        text: "PostgreSQL JSON函数", collapsed: true, items: [
          { text: 'array_to_json', link: '/database/postgreSQL/ref/array_to_json.html' },
          { text: 'json_array_length', link: '/database/postgreSQL/ref/json_array_length.html' },
          { text: 'json_array_elements', link: '/database/postgreSQL/ref/json_array_elements.html' },
          { text: 'json_array_elements_text', link: '/database/postgreSQL/ref/json_array_elements_text.html' },
          { text: 'json_build_array', link: '/database/postgreSQL/ref/json_build_array.html' },
          { text: 'json_build_object', link: '/database/postgreSQL/ref/json_build_object.html' },
          { text: 'json_build_length', link: '/database/postgreSQL/ref/json_build_length.html' },
          { text: 'json_each', link: '/database/postgreSQL/ref/json_each.html' },
          { text: 'json_each_text', link: '/database/postgreSQL/ref/json_each_text.html' },
          { text: 'json_extract_path', link: '/database/postgreSQL/ref/json_extract_path.html' },
          { text: 'json_extract_path_text', link: '/database/postgreSQL/ref/json_extract_path_text.html' },
          { text: 'json_object_keys', link: '/database/postgreSQL/ref/json_object_keys.html' },
          { text: 'json_object', link: '/database/postgreSQL/ref/json_object.html' },
          { text: 'json_populate_record', link: '/database/postgreSQL/ref/json_populate_record.html' },
          { text: 'json_populate_recordset', link: '/database/postgreSQL/ref/json_populate_recordset.html' },
          { text: 'json_strip_nulls', link: '/database/postgreSQL/ref/json_strip_nulls.html' },
          { text: 'json_to_record', link: '/database/postgreSQL/ref/json_to_record.html' },
          { text: 'json_to_recordset', link: '/database/postgreSQL/ref/json_to_recordset.html' },
          { text: 'json_typeof', link: '/database/postgreSQL/ref/json_typeof.html' },
          { text: 'jsonb_array_length', link: '/database/postgreSQL/ref/jsonb_array_length.html' },
          { text: 'jsonb_array_elements_text', link: '/database/postgreSQL/ref/jsonb_array_elements_text.html' },
          { text: 'jsonb_array_elements', link: '/database/postgreSQL/ref/jsonb_array_elements.html' },
          { text: 'jsonb_build_array', link: '/database/postgreSQL/ref/jsonb_build_array.html' },
          { text: 'jsonb_build_object', link: '/database/postgreSQL/ref/jsonb_build_object.html' },
          { text: 'jsonb_each', link: '/database/postgreSQL/ref/jsonb_each.html' },
          { text: 'jsonb_each_text', link: '/database/postgreSQL/ref/jsonb_each_text.html' },
          { text: 'jsonb_extract_path', link: '/database/postgreSQL/ref/jsonb_extract_path.html' },
          { text: 'jsonb_extract_path_text', link: '/database/postgreSQL/ref/jsonb_extract_path_text.html' },
          { text: 'jsonb_insert', link: '/database/postgreSQL/ref/jsonb_insert.html' },
          { text: 'jsonb_object', link: '/database/postgreSQL/ref/jsonb_object.html' },
          { text: 'jsonb_object_keys', link: '/database/postgreSQL/ref/jsonb_object_keys.html' },
          { text: 'jsonb_path_exists', link: '/database/postgreSQL/ref/jsonb_path_exists.html' },
          { text: 'jsonb_path_exists_tz', link: '/database/postgreSQL/ref/jsonb_path_exists_tz.html' },
          { text: 'jsonb_path_match', link: '/database/postgreSQL/ref/jsonb_path_match.html' },
          { text: 'jsonb_path_match_tz', link: '/database/postgreSQL/ref/jsonb_path_match_tz.html' },
          { text: 'jsonb_path_query', link: '/database/postgreSQL/ref/jsonb_path_query.html' },
          { text: 'jsonb_path_query_array', link: '/database/postgreSQL/ref/jsonb_path_query_array.html' },
          { text: 'jsonb_path_query_array_tz', link: '/database/postgreSQL/ref/jsonb_path_query_array_tz.html' },
          { text: 'jsonb_path_query_first', link: '/database/postgreSQL/ref/jsonb_path_query_first.html' },
          { text: 'jsonb_path_query_first_tz', link: '/database/postgreSQL/ref/jsonb_path_query_first_tz.html' },
          { text: 'jsonb_path_query_tz', link: '/database/postgreSQL/ref/jsonb_path_query_tz.html' },
          { text: 'jsonb_populate_record', link: '/database/postgreSQL/ref/jsonb_populate_record.html' },
          { text: 'jsonb_populate_recordset', link: '/database/postgreSQL/ref/jsonb_populate_recordset.html' },
          { text: 'jsonb_pretty', link: '/database/postgreSQL/ref/jsonb_pretty.html' },
          { text: 'jsonb_set', link: '/database/postgreSQL/ref/jsonb_set.html' },
          { text: 'jsonb_set_lax', link: '/database/postgreSQL/ref/jsonb_set_lax.html' },
          { text: 'jsonb_strip_nulls', link: '/database/postgreSQL/ref/jsonb_strip_nulls.html' },
          { text: 'jsonb_to_record', link: '/database/postgreSQL/ref/jsonb_to_record.html' },
          { text: 'jsonb_to_recordset', link: '/database/postgreSQL/ref/jsonb_to_recordset.html' },
          { text: 'jsonb_typeof', link: '/database/postgreSQL/ref/jsonb_typeof.html' },
          { text: 'row_to_json', link: '/database/postgreSQL/ref/row_to_json.html' },
          { text: 'to_json', link: '/database/postgreSQL/ref/to_json.html' },
          { text: 'to_jsonb', link: '/database/postgreSQL/ref/to_jsonb.html' },
        ]
      },
      {
        text: 'PostgreSQL 窗口函数', collapsed: true, items: [
          { text: 'cume_dist最高或最低百分比数量的记录', link: '/database/postgreSQL/ref/cume_dist.html' },
          { text: 'dense_rank当前行所在的分区内的排名', link: '/database/postgreSQL/ref/dense_rank.html' },
          { text: 'rank', link: '/database/postgreSQL/ref/rank.html' },
          { text: 'percent_rank', link: '/database/postgreSQL/ref/percent_rank.html' },
          { text: 'row_number', link: '/database/postgreSQL/ref/row_number.html' },
          { text: 'first_value', link: '/database/postgreSQL/ref/first_value.html' },
          { text: 'last_value', link: '/database/postgreSQL/ref/last_value.html' },
          { text: 'lag下一行的值', link: '/database/postgreSQL/ref/lag.html' },
          { text: 'lead上一行的值', link: '/database/postgreSQL/ref/lead.html' },
          { text: 'nth_value', link: '/database/postgreSQL/ref/nth_value.html' },
          { text: 'ntile', link: '/database/postgreSQL/ref/ntile.html' },
        ]
      },
      {
        text: 'PostgreSQL 聚合函数', collapsed: true, items: [
          { text: 'avg', link: '/database/postgreSQL/ref/avg.html' },
          { text: 'count', link: '/database/postgreSQL/ref/count.html' },
          { text: 'max', link: '/database/postgreSQL/ref/max.html' },
          { text: 'min', link: '/database/postgreSQL/ref/min.html' },
          { text: 'sum', link: '/database/postgreSQL/ref/sum.html' },
          { text: 'array_agg', link: '/database/postgreSQL/ref/array_agg.html' },
          { text: 'bit_and', link: '/database/postgreSQL/ref/bit_and.html' },
          { text: 'bit_or', link: '/database/postgreSQL/ref/bit_or.html' },
          { text: 'bit_xor', link: '/database/postgreSQL/ref/bit_xor.html' },
          { text: 'bool_and', link: '/database/postgreSQL/ref/bool_and.html' },
          { text: 'bool_or', link: '/database/postgreSQL/ref/bool_or.html' },
          { text: 'count', link: '/database/postgreSQL/ref/count.html' },
          { text: 'every', link: '/database/postgreSQL/ref/every.html' },
          { text: 'json_agg', link: '/database/postgreSQL/ref/json_agg.html' },
          { text: 'json_object_agg', link: '/database/postgreSQL/ref/json_object_agg.html' },
          { text: 'jsonb_agg', link: '/database/postgreSQL/ref/jsonb_agg.html' },
          { text: 'jsonb_object_agg', link: '/database/postgreSQL/ref/jsonb_object_agg.html' },
          { text: 'range_agg', link: '/database/postgreSQL/ref/range_agg.html' },
          { text: 'range_intersect_agg', link: '/database/postgreSQL/ref/range_intersect_agg.html' },
          { text: 'stddev', link: '/database/postgreSQL/ref/stddev.html' },
          { text: 'stddev_pop', link: '/database/postgreSQL/ref/stddev_pop.html' },
          { text: 'stddev_samp', link: '/database/postgreSQL/ref/stddev_samp.html' },
          { text: 'string_agg', link: '/database/postgreSQL/ref/string_agg.html' },
          { text: 'var_pop', link: '/database/postgreSQL/ref/var_pop.html' },
          { text: 'var_samp', link: '/database/postgreSQL/ref/var_samp.html' },
          { text: 'variance', link: '/database/postgreSQL/ref/variance.html' },
        ]
      },
      {
        text: 'PostgreSQL 数组函数', collapsed: true, items: [
          { text: 'array_append', link: '/database/postgreSQL/ref/array_append.html' },
          { text: 'array_cat数组连接', link: '/database/postgreSQL/ref/array_cat.html' },
          { text: 'array_dims数组的维度', link: '/database/postgreSQL/ref/array_dims.html' },
          { text: 'array_fill', link: '/database/postgreSQL/ref/array_fill.html' },
          { text: 'array_length', link: '/database/postgreSQL/ref/array_length.html' },
          { text: 'array_lower', link: '/database/postgreSQL/ref/array_lower.html' },
          { text: 'array_ndims', link: '/database/postgreSQL/ref/array_ndims.html' },
          { text: 'array_position第一次出现的下标', link: '/database/postgreSQL/ref/array_position.html' },
          { text: 'array_positions', link: '/database/postgreSQL/ref/array_positions.html' },
          { text: 'array_prepend', link: '/database/postgreSQL/ref/array_prepend.html' },
          { text: 'array_remove', link: '/database/postgreSQL/ref/array_remove.html' },
          { text: 'array_replace', link: '/database/postgreSQL/ref/array_replace.html' },
          { text: 'array_to_string', link: '/database/postgreSQL/ref/array_to_string.html' },
          { text: 'array_upper', link: '/database/postgreSQL/ref/array_upper.html' },
          { text: 'cardinality', link: '/database/postgreSQL/ref/cardinality.html' },
          { text: 'trim_array', link: '/database/postgreSQL/ref/trim_array.html' },
          { text: 'unnest展开数组', link: '/database/postgreSQL/ref/unnest.html' },
        ]
      },
      {
        text: 'PostgreSQL 序列操作函数', collapsed: true, items: [
          { text: 'nextval', link: '/database/postgreSQL/ref/nextval.html' },
          { text: 'currval', link: '/database/postgreSQL/ref/currval.html' },
          { text: 'lastval', link: '/database/postgreSQL/ref/lastval.html' },
          { text: 'setval', link: '/database/postgreSQL/ref/setval.html' },
        ]
      },
      {
        text: 'PostgreSQL 枚举函数', collapsed: true, items: [
          { text: 'enum_first', link: '/database/postgreSQL/ref/enum_first.html' },
          { text: 'enum_last', link: '/database/postgreSQL/ref/enum_last.html' },
          { text: 'enum_range', link: '/database/postgreSQL/ref/enum_range.html' },
        ]
      },
      {
        text: 'PostgreSQL 返回集合函数', collapsed: true, items: [
          { text: 'generate_series', link: '/database/postgreSQL/ref/generate_series.html' },
          { text: 'generate_subscripts', link: '/database/postgreSQL/ref/generate_subscripts.html' },
        ]
      },
      {
        text: 'PostgreSQL 范围函数', collapsed: true, items: [
          { text: 'isempty', link: '/database/postgreSQL/ref/isempty.html' },
          { text: 'lower_inc', link: '/database/postgreSQL/ref/lower_inc.html' },
          { text: 'lower_inf', link: '/database/postgreSQL/ref/lower_inf.html' },
          { text: 'lower', link: '/database/postgreSQL/ref/lower(range).html' },
          { text: 'multirange', link: '/database/postgreSQL/ref/multirange.html' },
          { text: 'range_merge', link: '/database/postgreSQL/ref/range_merge.html' },
          { text: 'unnest', link: '/database/postgreSQL/ref/unnest(anymultirange).html' },
          { text: 'upper_inc', link: '/database/postgreSQL/ref/upper_inc.html' },
          { text: 'upper_inf', link: '/database/postgreSQL/ref/upper_inf.html' },
          { text: 'upper', link: '/database/postgreSQL/ref/upper(range).html' },
        ]
      },
      {
        text: 'PostgreSQL 会话信息函数', collapsed: true, items: [
          { text: 'current_catalog', link: '/database/postgreSQL/ref/current_catalog.html' },
          { text: 'current_database', link: '/database/postgreSQL/ref/current_database.html' },
          { text: 'current_query', link: '/database/postgreSQL/ref/current_query.html' },
          { text: 'current_role', link: '/database/postgreSQL/ref/current_role.html' },
          { text: 'current_schema', link: '/database/postgreSQL/ref/current_schema.html' },
          { text: 'current_schemas', link: '/database/postgreSQL/ref/current_schemas.html' },
          { text: 'current_user', link: '/database/postgreSQL/ref/current_user.html' },
          { text: 'inet_client_addr', link: '/database/postgreSQL/ref/inet_client_addr.html' },
          { text: 'inet_client_port', link: '/database/postgreSQL/ref/inet_client_port.html' },
          { text: 'inet_server_addr', link: '/database/postgreSQL/ref/inet_server_addr.html' },
          { text: 'inet_server_port', link: '/database/postgreSQL/ref/inet_server_port.html' },
          { text: 'pg_backend_pid', link: '/database/postgreSQL/ref/pg_backend_pid.html' },
          { text: 'pg_blocking_pids', link: '/database/postgreSQL/ref/pg_blocking_pids.html' },
          { text: 'pg_conf_load_time', link: '/database/postgreSQL/ref/pg_conf_load_time.html' },
          { text: 'pg_current_logfile', link: '/database/postgreSQL/ref/pg_current_logfile.html' },
          { text: 'pg_is_other_temp_schema', link: '/database/postgreSQL/ref/pg_is_other_temp_schema.html' },
          { text: 'pg_jit_available', link: '/database/postgreSQL/ref/pg_jit_available.html' },
          { text: 'pg_listening_channels', link: '/database/postgreSQL/ref/pg_listening_channels.html' },
          { text: 'pg_my_temp_schema', link: '/database/postgreSQL/ref/pg_my_temp_schema.html' },
          { text: 'pg_notification_queue_usage', link: '/database/postgreSQL/ref/pg_notification_queue_usage.html' },
          { text: 'pg_postmaster_start_time', link: '/database/postgreSQL/ref/pg_postmaster_start_time.html' },
          { text: 'pg_trigger_depth', link: '/database/postgreSQL/ref/pg_trigger_depth.html' },
          { text: 'session_user', link: '/database/postgreSQL/ref/session_user.html' },
          { text: 'user', link: '/database/postgreSQL/ref/user.html' },
          { text: 'version', link: '/database/postgreSQL/ref/version.html' },
        ]
      },
      {
        text: 'PostgreSQL 几何函数', collapsed: true, items: [
          { text: 'area()', link: '/database/postgreSQL/ref/area().html' },
          { text: 'bound_box()', link: '/database/postgreSQL/ref/bound_box().html' },
          { text: 'box(circle)', link: '/database/postgreSQL/ref/box(circle).html' },
          { text: 'box(point,point)', link: '/database/postgreSQL/ref/box(point,point).html' },
          { text: 'box(point)', link: '/database/postgreSQL/ref/box(point).html' },
          { text: 'box(polygon)', link: '/database/postgreSQL/ref/box(polygon).html' },
          { text: 'center()', link: '/database/postgreSQL/ref/center().html' },
          { text: 'circle()', link: '/database/postgreSQL/ref/circle().html' },
          { text: 'circle(box)', link: '/database/postgreSQL/ref/circle(box).html' },
          { text: 'circle(polygon)', link: '/database/postgreSQL/ref/circle(polygon).html' },
          { text: 'diagonal()', link: '/database/postgreSQL/ref/diagonal().html' },
          { text: 'diameter()', link: '/database/postgreSQL/ref/diameter().html' },
          { text: 'height()', link: '/database/postgreSQL/ref/height().html' },
          { text: 'isclosed()', link: '/database/postgreSQL/ref/isclosed().html' },
          { text: 'isopen()', link: '/database/postgreSQL/ref/isopen().html' },
          { text: 'length()', link: '/database/postgreSQL/ref/length().html' },
          { text: 'line()', link: '/database/postgreSQL/ref/line().html' },
          { text: 'lseg(box)', link: '/database/postgreSQL/ref/lseg(box).html' },
          { text: 'lseg(point,point)', link: '/database/postgreSQL/ref/lseg(point,point).html' },
          { text: 'npoints()', link: '/database/postgreSQL/ref/npoints().html' },
          { text: 'path(polygon)', link: '/database/postgreSQL/ref/path(polygon).html' },
          { text: 'pclose()', link: '/database/postgreSQL/ref/pclose().html' },
          { text: 'point()', link: '/database/postgreSQL/ref/point().html' },
          { text: 'point(box)', link: '/database/postgreSQL/ref/point(box).html' },
          { text: 'point(circle)', link: '/database/postgreSQL/ref/point(circle).html' },
          { text: 'point(lseg)', link: '/database/postgreSQL/ref/point(lseg).html' },
          { text: 'point(polygon)', link: '/database/postgreSQL/ref/point(polygon).html' },
          { text: 'polygon(box)', link: '/database/postgreSQL/ref/polygon(box).html' },
          { text: 'polygon(circle)', link: '/database/postgreSQL/ref/polygon(circle).html' },
          { text: 'polygon(integer, circle)', link: '/database/postgreSQL/ref/polygon(integer,circle).html' },
          { text: 'polygon(path)', link: '/database/postgreSQL/ref/polygon(path).html' },
          { text: 'popen()', link: '/database/postgreSQL/ref/popen().html' },
          { text: 'radius()', link: '/database/postgreSQL/ref/radius().html' },
          { text: 'slope()', link: '/database/postgreSQL/ref/slope().html' },
          { text: 'width()', link: '/database/postgreSQL/ref/width().html' },
        ]
      }
    ],

    "/database/postgreSQL/": [
      {
        text: "PostgreSQL起步", collapsed: true, items: [
          { text: '安装 PostgreSQL 14', link: '/database/postgreSQL/index.html' },
          { text: '示例数据库', link: '/database/postgreSQL/示例数据库.html' },
        ]
      },
      {
        text: "PostgreSQL 基础", collapsed: true, items: [
          { text: 'SELECT', link: '/database/postgreSQL/base/select.html' },
          { text: 'WHERE', link: '/database/postgreSQL/base/WHERE.html' },
          { text: 'ORDER BY', link: '/database/postgreSQL/base/ORDER_BY.html' },
          { text: 'FETCH', link: '/database/postgreSQL/base/FETCH.html' },
          { text: 'LIMIT', link: '/database/postgreSQL/base/LIMIT.html' },
          { text: 'OFFSET', link: '/database/postgreSQL/base/OFFSET.html' },
          { text: 'DISTINCT', link: '/database/postgreSQL/base/DISTINCT.html' },
          { text: '列别名', link: '/database/postgreSQL/base/列别名.html' },
          { text: '表别名', link: '/database/postgreSQL/base/表别名.html' },
          { text: 'IN', link: '/database/postgreSQL/base/IN.html' },
          { text: 'BETWEEN', link: '/database/postgreSQL/base/BETWEEN.html' },
          { text: 'LIKE', link: '/database/postgreSQL/base/LIKE.html' },
          { text: 'IS NULL', link: '/database/postgreSQL/base/IS_NULL.html' },
          { text: 'EXISTS', link: '/database/postgreSQL/base/EXISTS.html' },
          { text: 'ALL', link: '/database/postgreSQL/base/ALL.html' },
          { text: 'ANY', link: '/database/postgreSQL/base/ANY.html' },
          { text: 'GROUP BY', link: '/database/postgreSQL/base/GROUP_BY.html' },
          { text: 'HAVING', link: '/database/postgreSQL/base/HAVING.html' },
          { text: 'GROUPING SETS', link: '/database/postgreSQL/base/GROUPING_SETS.html' },
          { text: 'ROLLUP', link: '/database/postgreSQL/base/ROLLUP.html' },
          { text: 'CUBE', link: '/database/postgreSQL/base/CUBE.html' },
          { text: 'JOIN', link: '/database/postgreSQL/base/JOIN.html' },
          { text: '子查询', link: '/database/postgreSQL/base/子查询.html' },
          { text: 'CTE', link: '/database/postgreSQL/base/CTE.html' },
          { text: 'UNION', link: '/database/postgreSQL/base/UNION.html' },
          { text: 'INTERSECT', link: '/database/postgreSQL/base/INTERSECT.html' },
          { text: 'EXCEPT', link: '/database/postgreSQL/base/EXCEPT.html' },
          { text: 'INSERT', link: '/database/postgreSQL/base/INSERT.html' },
          { text: 'INSERT ON CONFLICT', link: '/database/postgreSQL/base/INSERT_ON_CONFLICT.html' },
          { text: 'UPDATE', link: '/database/postgreSQL/base/UPDATE.html' },
          { text: 'UPDATE...FROM', link: '/database/postgreSQL/base/UPDATE_FROM.html' },
          { text: 'DELETE', link: '/database/postgreSQL/base/DELETE.html' },
          { text: '清空表', link: '/database/postgreSQL/base/清空表.html' },
          { text: 'CASE', link: '/database/postgreSQL/base/CASE.html' },
        ]
      },
      {
        text: "PostgreSQL数据库和表", collapsed: true, items: [
          { text: 'psql命令', link: '/database/postgreSQL/databaseAndTable/psql命令.html' },
          { text: '列出数据库', link: '/database/postgreSQL/databaseAndTable/列出数据库.html' },
          { text: '复制数据库', link: '/database/postgreSQL/databaseAndTable/复制数据库.html' },
          { text: '查看空间', link: '/database/postgreSQL/databaseAndTable/查看空间.html' },
          { text: '创建数据库', link: '/database/postgreSQL/databaseAndTable/创建数据库.html' },
          { text: '删除数据库', link: '/database/postgreSQL/databaseAndTable/删除数据库.html' },
          { text: '修改数据库', link: '/database/postgreSQL/databaseAndTable/修改数据库.html' },
          { text: '重命名数据库', link: '/database/postgreSQL/databaseAndTable/重命名数据库.html' },
          { text: '备份和恢复', link: '/database/postgreSQL/databaseAndTable/备份和恢复.html' },
          { text: 'EXPLAIN', link: '/database/postgreSQL/databaseAndTable/EXPLAIN.html' },
          { text: '重置密码', link: '/database/postgreSQL/databaseAndTable/重置密码.html' },
          { text: '列出表', link: '/database/postgreSQL/databaseAndTable/列出表.html' },
          { text: '查看表', link: '/database/postgreSQL/databaseAndTable/查看表.html' },
          { text: '复制表', link: '/database/postgreSQL/databaseAndTable/复制表.html' },
          { text: '创建表', link: '/database/postgreSQL/databaseAndTable/创建表.html' },
          { text: '删除表', link: '/database/postgreSQL/databaseAndTable/删除表.html' },
          { text: '修改表', link: '/database/postgreSQL/databaseAndTable/修改表.html' },
          { text: '重命名表', link: '/database/postgreSQL/databaseAndTable/重命名表.html' },
          { text: '添加列', link: '/database/postgreSQL/databaseAndTable/添加列.html' },
          { text: '修改列', link: '/database/postgreSQL/databaseAndTable/修改列.html' },
          { text: '删除列', link: '/database/postgreSQL/databaseAndTable/删除列.html' },
          { text: '重命名列', link: '/database/postgreSQL/databaseAndTable/重命名列.html' },
          { text: '主键', link: '/database/postgreSQL/databaseAndTable/主键.html' },
          { text: '外键', link: '/database/postgreSQL/databaseAndTable/外键.html' },
          { text: 'NOT NULL', link: '/database/postgreSQL/databaseAndTable/NOT_NULL.html' },
          { text: '唯一约束', link: '/database/postgreSQL/databaseAndTable/唯一约束.html' },
          { text: 'CHECK 约束', link: '/database/postgreSQL/databaseAndTable/CHECK约束.html' },
          { text: '生成列', link: '/database/postgreSQL/databaseAndTable/生成列.html' },
          { text: '标识列', link: '/database/postgreSQL/databaseAndTable/标识列.html' },
          { text: 'SERIAL自增列', link: '/database/postgreSQL/databaseAndTable/SERIAL自增列.html' },
          { text: 'SEQUENCE 序列生成器', link: '/database/postgreSQL/databaseAndTable/SEQUENCE序列生成器.html' },
          { text: '临时表', link: '/database/postgreSQL/databaseAndTable/临时表.html' },
          { text: 'SELECT INTO', link: '/database/postgreSQL/databaseAndTable/SELECT_INTO.html' },
          { text: '事务', link: '/database/postgreSQL/databaseAndTable/事务.html' },
          { text: '架构', link: '/database/postgreSQL/databaseAndTable/架构.html' },
        ]
      },
      {
        text: "数据类型", collapsed: true, items: [
          { text: '字符类型', link: '/database/postgreSQL/dataType/字符类型.html' },
          { text: '整数类型', link: '/database/postgreSQL/dataType/整数类型.html' },
          { text: '浮点类型', link: '/database/postgreSQL/dataType/浮点类型.html' },
          { text: 'NUMERIC', link: '/database/postgreSQL/dataType/NUMERIC.html' },
          { text: '布尔类型', link: '/database/postgreSQL/dataType/布尔类型.html' },
          { text: 'DATE', link: '/database/postgreSQL/dataType/DATE.html' },
          { text: 'TIME', link: '/database/postgreSQL/dataType/TIME.html' },
          { text: '时间戳', link: '/database/postgreSQL/dataType/时间戳.html' },
          { text: 'INTERVAL', link: '/database/postgreSQL/dataType/INTERVAL.html' },
          { text: 'ARRAY', link: '/database/postgreSQL/dataType/ARRAY.html' },
          { text: 'JSON', link: '/database/postgreSQL/dataType/JSON.html' },
          { text: 'UUID', link: '/database/postgreSQL/dataType/UUID.html' },
          { text: 'HSTORE', link: '/database/postgreSQL/dataType/HSTORE.html' },
          { text: '范围', link: '/database/postgreSQL/dataType/范围.html' },
          { text: '用户自定义类型', link: '/database/postgreSQL/dataType/用户自定义类型.html' },
        ]
      },
      {
        text: "索引", collapsed: true, items: [
          { text: '索引类型', link: '/database/postgreSQL/index/索引类型.html' },
          { text: '创建索引', link: '/database/postgreSQL/index/创建索引.html' },
          { text: '删除索引', link: '/database/postgreSQL/index/删除索引.html' },
          { text: '查看索引', link: '/database/postgreSQL/index/查看索引.html' },
          { text: '多列索引', link: '/database/postgreSQL/index/多列索引.html' },
          { text: '唯一索引', link: '/database/postgreSQL/index/唯一索引.html' },
          { text: '表达式索引', link: '/database/postgreSQL/index/表达式索引.html' },
          { text: '部分索引', link: '/database/postgreSQL/index/部分索引.html' },
          { text: '重建索引', link: '/database/postgreSQL/index/重建索引.html' },
        ]
      },
      {
        text: "条件表达式", collapsed: true, items: [
          { text: 'CASE', link: '/database/postgreSQL/condition/CASE.html' },
          { text: 'COALESCE 返回参数列表中第一个非空值', link: '/database/postgreSQL/condition/COALESCE.html' },
          { text: 'NULLIF 两个参数相等时返回NULL', link: '/database/postgreSQL/condition/NULLIF.html' },
          { text: 'GREATEST 最大值', link: '/database/postgreSQL/condition/GREATEST.html' },
          { text: 'LEAST 最小值', link: '/database/postgreSQL/condition/LEAST.html' },
        ]
      }
    ],
    "/database/": [
      { text: 'mongodb', link: '/database/mongodb/README.html' },
      {
        text: 'Elasticsearch',
        items: [
          { text: '概述', link: '/database/elasticsearch/README.html' },
          { text: 'es安装与使用', link: '/database/elasticsearch/es安装与使用.html' },
          { text: '基础功能', link: '/database/elasticsearch/基础功能.html' },
          { text: '批量操作', link: '/database/elasticsearch/批量操作.html' },
          { text: '索引模版', link: '/database/elasticsearch/索引模版.html' },
          { text: 'ES高级查询', link: '/database/elasticsearch/ES高级查询.html' },
          { text: 'ES检索原理分析', link: '/database/elasticsearch/ES检索原理分析.html' },
          { text: 'kibana安装与使用', link: '/database/elasticsearch/kibana安装与使用.html' },
          { text: 'GOLANG操作ES', link: '/database/elasticsearch/GOLANG操作ES.html' },
        ]
      },
      { text: 'Runtime API Examples', link: '/api-examples' }
    ],
    "/golang/": [
      {
        text: "基础知识", items: [
          { text: '泛型', link: '/golang/base/泛型.html' },
          { text: '反射', link: '/golang/base/反射.html' },
        ]
      },
      {
        text: "GIN", collapsed: false, items: [
          { text: 'go-validator 验证规则', link: '/golang/gin/validator.html' }
        ]
      },
      {
        text: "CMD", items: [
          { text: 'stringer', link: '/golang/cmd/stringer.html' },
        ]
      },
      {
        text: "TOOL", items: [
          { text: '抽象语法树ast库使用', link: '/golang/tool/抽象语法树ast库使用.html' },
        ]
      }
    ],
    "/python/": [
      {
        text: "基础知识", items: [
          { text: '基础', link: '/python/base/README.html' }
        ]
      },
      {
        text: "CMD", items: [
          { text: 'stringer', link: '/golang/cmd/stringer.html' },
        ]
      },
      {
        text: "TOOL", items: [
          { text: '抽象语法树ast库使用', link: '/golang/tool/抽象语法树ast库使用.html' },
        ]
      }
    ],
    "/productDesgin/": [
      {
        text: "UML", items: [
          { text: '时序图', link: '/productDesgin/uml/时序图.html' },
        ]
      },
      {
        text: "思维导图", items: [
          { text: '八大思维图示法', link: '/productDesgin/八大思维图示法.html' },
        ]
      }
    ],
    "/lvmeng/": [
      {
        text: "lvmeng", items: [
          { text: '环境依赖', link: '/lvmeng/环境依赖.html' },
          { text: 'AI功能配置', link: '/lvmeng/ai_function_configuration_guide.html' },
        ]
      },
    ],
    "/vue/css/": [
      {
        text: 'CSS 属性', collapsed: true, items: [
          { text: 'align-content', link: '/vue/css/attr/align-content.html' },
          { text: 'align-items', link: '/vue/css/attr/align-items.html' },
          { text: 'align-self', link: '/vue/css/attr/align-self.html' },
          { text: 'all', link: '/vue/css/attr/all.html' },
          {
            text: 'animation*', collapsed: true, items: [
              { text: 'animation', link: '/vue/css/attr/animation.html' },
              { text: 'animation-delay', link: '/vue/css/attr/animation-delay.html' },
              { text: 'animation-direction', link: '/vue/css/attr/animation-direction.html' },
              { text: 'animation-duration', link: '/vue/css/attr/animation-duration.html' },
              { text: 'animation-fill-mode', link: '/vue/css/attr/animation-fill-mode.html' },
              { text: 'animation-iteration-count', link: '/vue/css/attr/animation-iteration-count.html' },
              { text: 'animation-name', link: '/vue/css/attr/animation-name.html' },
              { text: 'animation-play-state', link: '/vue/css/attr/animation-play-state.html' },
              { text: 'animation-timing-function', link: '/vue/css/attr/animation-timing-function.html' },
            ]
          },

          { text: 'backface-visibility背面可见性', link: '/vue/css/attr/backface-visibility.html' },
          {
            text: 'background*', collapsed: true, items: [
              { text: 'background', link: '/vue/css/attr/background.html' },
              { text: 'background-attachment', link: '/vue/css/attr/background-attachment.html' },
              { text: 'background-blend-mode', link: '/vue/css/attr/background-blend-mode.html' },
              { text: 'background-clip', link: '/vue/css/attr/background-clip.html' },
              { text: 'background-color', link: '/vue/css/attr/background-color.html' },
              { text: 'background-image', link: '/vue/css/attr/background-image.html' },
              { text: 'background-origin', link: '/vue/css/attr/background-origin.html' },
              { text: 'background-position', link: '/vue/css/attr/background-position.html' },
              { text: 'background-repeat', link: '/vue/css/attr/background-repeat.html' },
              { text: 'background-size', link: '/vue/css/attr/background-size.html' },
            ]
          },

          {
            text: 'border', collapsed: true, items: [{ text: 'border', link: '/vue/css/attr/border.html' },
            { text: 'border-bottom', link: '/vue/css/attr/border-bottom.html' },
            { text: 'border-bottom-color', link: '/vue/css/attr/border-bottom-color.html' },
            { text: 'border-bottom-left-radius', link: '/vue/css/attr/border-bottom-left-radius.html' },
            { text: 'border-bottom-right-radius', link: '/vue/css/attr/border-bottom-right-radius.html' },
            { text: 'border-bottom-style', link: '/vue/css/attr/border-bottom-style.html' },
            { text: 'border-bottom-width', link: '/vue/css/attr/border-bottom-width.html' },
            { text: 'border-collapse', link: '/vue/css/attr/border-collapse.html' },
            { text: 'border-color', link: '/vue/css/attr/border-color.html' },
            { text: 'border-image', link: '/vue/css/attr/border-image.html' },
            { text: 'border-image-outset', link: '/vue/css/attr/border-image-outset.html' },
            { text: 'border-image-repeat', link: '/vue/css/attr/border-image-repeat.html' },
            { text: 'border-image-slice', link: '/vue/css/attr/border-image-slice.html' },
            { text: 'border-image-source', link: '/vue/css/attr/border-image-source.html' },
            { text: 'border-image-width', link: '/vue/css/attr/border-image-width.html' },
            { text: 'border-left', link: '/vue/css/attr/border-left.html' },
            { text: 'border-left-color', link: '/vue/css/attr/border-left-color.html' },
            { text: 'border-left-style', link: '/vue/css/attr/border-left-style.html' },
            { text: 'border-left-width', link: '/vue/css/attr/border-left-width.html' },
            { text: 'border-radius', link: '/vue/css/attr/border-radius.html' },
            { text: 'border-right', link: '/vue/css/attr/border-right.html' },
            { text: 'border-right-color', link: '/vue/css/attr/border-right-color.html' },
            { text: 'border-right-style', link: '/vue/css/attr/border-right-style.html' },
            { text: 'border-right-width', link: '/vue/css/attr/border-right-width.html' },
            { text: 'border-spacing', link: '/vue/css/attr/border-spacing.html' },
            { text: 'border-style', link: '/vue/css/attr/border-style.html' },
            { text: 'border-top', link: '/vue/css/attr/border-top.html' },
            { text: 'border-top-color', link: '/vue/css/attr/border-top-color.html' },
            { text: 'border-top-left-radius', link: '/vue/css/attr/border-top-left-radius.html' },
            { text: 'border-top-right-radius', link: '/vue/css/attr/border-top-right-radius.html' },
            { text: 'border-top-style', link: '/vue/css/attr/border-top-style.html' },
            { text: 'border-top-width', link: '/vue/css/attr/border-top-width.html' },]
          },

          { text: 'box-decoration-break', link: '/vue/css/attr/box-decoration-break.html' },
          { text: 'box-shadow', link: '/vue/css/attr/box-shadow.html' },
          { text: 'box-sizing', link: '/vue/css/attr/box-sizing.html' },
          { text: 'break-after', link: '/vue/css/attr/break-after.html' },
          { text: 'break-before', link: '/vue/css/attr/break-before.html' },
          { text: 'break-inside', link: '/vue/css/attr/break-inside.html' },
          { text: 'caption-side', link: '/vue/css/attr/caption-side.html' },
          { text: 'caret-color', link: '/vue/css/attr/caret-color.html' },
          { text: 'clear', link: '/vue/css/attr/clear.html' },
          { text: 'clip-path', link: '/vue/css/attr/clip-path.html' },
          { text: 'color', link: '/vue/css/attr/color.html' },
          { text: 'column-count', link: '/vue/css/attr/column-count.html' },
          { text: 'column-fill', link: '/vue/css/attr/column-fill.html' },
          { text: 'column-rule', link: '/vue/css/attr/column-rule.html' },
          { text: 'column-rule-color', link: '/vue/css/attr/column-rule-color.html' },
          { text: 'column-rule-style', link: '/vue/css/attr/column-rule-style.html' },
          { text: 'column-rule-width', link: '/vue/css/attr/column-rule-width.html' },
          { text: 'column-span', link: '/vue/css/attr/column-span.html' },
          { text: 'column-width', link: '/vue/css/attr/column-width.html' },
          { text: 'columns', link: '/vue/css/attr/columns.html' },
          { text: 'content', link: '/vue/css/attr/content.html' },
          { text: 'counter-increment', link: '/vue/css/attr/counter-increment.html' },
          { text: 'counter-reset', link: '/vue/css/attr/counter-reset.html' },
          { text: 'counter-set', link: '/vue/css/attr/counter-set.html' },
          { text: 'cursor', link: '/vue/css/attr/cursor.html' },
          { text: 'direction', link: '/vue/css/attr/direction.html' },
          { text: 'display', link: '/vue/css/attr/display.html' },
          { text: 'empty-cells', link: '/vue/css/attr/empty-cells.html' },
          { text: 'filter', link: '/vue/css/attr/filter.html' },
          { text: 'flex', link: '/vue/css/attr/flex.html' },
          { text: 'flex-grow', link: '/vue/css/attr/flex-grow.html' },
          { text: 'flex-shrink', link: '/vue/css/attr/flex-shrink.html' },
          { text: 'flex-basis', link: '/vue/css/attr/flex-basis.html' },
          { text: 'flex-direction', link: '/vue/css/attr/flex-direction.html' },
          { text: 'flex-wrap', link: '/vue/css/attr/flex-wrap.html' },
          { text: 'flex-flow', link: '/vue/css/attr/flex-flow.html' },
          { text: 'float', link: '/vue/css/attr/float.html' },
          { text: 'font', link: '/vue/css/attr/font.html' },
          {
            text: 'grid', collapsed: true, items: [
              { text: 'grid', link: '/vue/css/attr/grid.html' },
              { text: 'grid-area', link: '/vue/css/attr/grid-area.html' },
              { text: 'grid-auto-columns', link: '/vue/css/attr/grid-auto-columns.html' },
              { text: 'grid-auto-flow', link: '/vue/css/attr/grid-auto-flow.html' },
              { text: 'grid-auto-rows', link: '/vue/css/attr/grid-auto-rows.html' },
              { text: 'grid-column', link: '/vue/css/attr/grid-column.html' },
              { text: 'grid-column-end', link: '/vue/css/attr/grid-column-end.html' },
              { text: 'grid-column-gap', link: '/vue/css/attr/grid-column-gap.html' },
              { text: 'grid-column-start', link: '/vue/css/attr/grid-column-start.html' },
              { text: 'grid-gap', link: '/vue/css/attr/grid-gap.html' },
              { text: 'grid-row', link: '/vue/css/attr/grid-row.html' },
              { text: 'grid-row-end', link: '/vue/css/attr/grid-row-end.html' },
              { text: 'grid-row-gap', link: '/vue/css/attr/grid-row-gap.html' },
              { text: 'grid-row-start', link: '/vue/css/attr/grid-row-start.html' },
              { text: 'grid-template', link: '/vue/css/attr/grid-template.html' },
              { text: 'grid-template-areas', link: '/vue/css/attr/grid-template-areas.html' },
              { text: 'grid-template-rows', link: '/vue/css/attr/grid-template-rows.html' },
            ]
          },

          { text: 'height', link: '/vue/css/attr/height.html' },
          { text: 'hyphens连字符', link: '/vue/css/attr/hyphens.html' },
          { text: 'justify-content', link: '/vue/css/attr/justify-content.html' },
          { text: 'justify-items', link: '/vue/css/attr/justify-items.html' },
          { text: 'justify-self', link: '/vue/css/attr/justify-self.html' },
          { text: 'left', link: '/vue/css/attr/left.html' },
          { text: 'letter-spacing 字符间距', link: '/vue/css/attr/letter-spacing.html' },
          { text: 'line-break', link: '/vue/css/attr/line-break.html' },
          { text: 'line-height', link: '/vue/css/attr/line-height.html' },
          { text: 'list-style', link: '/vue/css/attr/list-style.html' },
          { text: 'list-style-image', link: '/vue/css/attr/list-style-image.html' },
          { text: 'list-style-position', link: '/vue/css/attr/list-style-position.html' },
          { text: 'list-style-type', link: '/vue/css/attr/list-style-type.html' },
          { text: 'margin', link: '/vue/css/attr/margin.html' },
          { text: 'max-height', link: '/vue/css/attr/max-height.html' },
          { text: 'max-width', link: '/vue/css/attr/max-width.html' },
          { text: 'min-height', link: '/vue/css/attr/min-height.html' },
          { text: 'min-width', link: '/vue/css/attr/min-width.html' },
          { text: 'mix-blend-mode 混合模式', link: '/vue/css/attr/mix-blend-mode.html' },
          { text: 'object-fit', link: '/vue/css/attr/object-fit.html' },
          { text: 'object-position', link: '/vue/css/attr/object-position.html' },
          { text: 'opacity', link: '/vue/css/attr/opacity.html' },
          { text: 'order', link: '/vue/css/attr/order.html' },
          { text: 'orphans最小行数', link: '/vue/css/attr/orphans.html' },
          { text: 'outline轮廓', link: '/vue/css/attr/outline.html' },
          { text: 'outline-color', link: '/vue/css/attr/outline-color.html' },
          { text: 'outline-offset', link: '/vue/css/attr/outline-offset.html' },
          { text: 'outline-style', link: '/vue/css/attr/outline-style.html' },
          { text: 'outline-width', link: '/vue/css/attr/outline-width.html' },
          { text: 'overflow', link: '/vue/css/attr/overflow.html' },
          { text: 'overflow-wrap', link: '/vue/css/attr/overflow-wrap.html' },
          { text: 'overflow-x', link: '/vue/css/attr/overflow-x.html' },
          { text: 'overflow-y', link: '/vue/css/attr/overflow-y.html' },
          { text: 'padding', link: '/vue/css/attr/padding.html' },
          { text: 'padding-bottom', link: '/vue/css/attr/padding-bottom.html' },
          { text: 'padding-left', link: '/vue/css/attr/padding-left.html' },
          { text: 'padding-right', link: '/vue/css/attr/padding-right.html' },
          { text: 'padding-top', link: '/vue/css/attr/padding-top.html' },
          { text: 'perspective视角/角度', link: '/vue/css/attr/perspective.html' },
          { text: 'perspective-origin视角原点', link: '/vue/css/attr/perspective-origin.html' },
          { text: 'place-content', link: '/vue/css/attr/place-content.html' },
          { text: 'place-items', link: '/vue/css/attr/place-items.html' },
          { text: 'place-self', link: '/vue/css/attr/place-self.html' },
          { text: 'position', link: '/vue/css/attr/position.html' },
          { text: 'quotes 引号', link: '/vue/css/attr/quotes.html' },
          { text: 'resize', link: '/vue/css/attr/resize.html' },
          { text: 'right', link: '/vue/css/attr/right.html' },
          { text: 'rotate', link: '/vue/css/attr/rotate.html' },
          { text: 'ruby-position', link: '/vue/css/attr/ruby-position.html' },
          { text: 'scale', link: '/vue/css/attr/scale.html' },
          {
            text: 'scroll*', collapsed: true, items: [
              { text: 'scroll-behavior', link: '/vue/css/attr/scroll-behavior.html' },
              { text: 'scroll-margin', link: '/vue/css/attr/scroll-margin.html' },
              { text: 'scroll-margin-block', link: '/vue/css/attr/scroll-margin-block.html' },
              { text: 'scroll-margin-block-end', link: '/vue/css/attr/scroll-margin-block-end.html' },
              { text: 'scroll-margin-block-start', link: '/vue/css/attr/scroll-margin-block-start.html' },
              { text: 'scroll-margin-bottom', link: '/vue/css/attr/scroll-margin-bottom.html' },
              { text: 'scroll-margin-inline', link: '/vue/css/attr/scroll-margin-inline.html' },
              { text: 'scroll-padding', link: '/vue/css/attr/scroll-padding.html' },
              { text: 'scroll-snap-align', link: '/vue/css/attr/scroll-snap-align.html' },
              { text: 'scroll-snap-stop', link: '/vue/css/attr/scroll-snap-stop.html' },
              { text: 'scroll-snap-type', link: '/vue/css/attr/scroll-snap-type.html' },
            ]
          },
          {
            text: 'scrollbar*', collapsed: true, items: [
              { text: 'scrollbar-color', link: '/vue/css/attr/scrollbar-color.html' },
              { text: 'scrollbar-gutter', link: '/vue/css/attr/scrollbar-gutter.html' },
              { text: 'scrollbar-width', link: '/vue/css/attr/scrollbar-width.html' },
            ]
          },
          {
            text: 'shape*', collapsed: true, items: [
              { text: 'shape-image-threshold', link: '/vue/css/attr/shape-image-threshold.html' },
              { text: 'shape-margin', link: '/vue/css/attr/shape-margin.html' },
              { text: 'shape-outside', link: '/vue/css/attr/shape-outside.html' },
            ]
          },
          { text: 'tab-size', link: '/vue/css/attr/tab-size.html' },
          { text: 'table-layout', link: '/vue/css/attr/table-layout.html' },
          {
            text: 'text*', collapsed: true, items: [
              { text: 'text-align', link: '/vue/css/attr/text-align.html' },
              { text: 'text-align-last', link: '/vue/css/attr/text-align-last.html' },
              { text: 'text-combine-upright', link: '/vue/css/attr/text-combine-upright.html' },
              { text: 'text-decoration', link: '/vue/css/attr/text-decoration.html' },
              { text: 'text-decoration-color', link: '/vue/css/attr/text-decoration-color.html' },
              { text: 'text-decoration-line', link: '/vue/css/attr/text-decoration-line.html' },
              { text: 'text-decoration-thickness', link: '/vue/css/attr/text-decoration-thickness.html' },
              { text: 'text-emphasis', link: '/vue/css/attr/text-emphasis.html' },
              { text: 'text-emphasis-color', link: '/vue/css/attr/text-emphasis-color.html' },
              { text: 'text-emphasis-position', link: '/vue/css/attr/text-emphasis-position.html' },
              { text: 'text-emphasis-style', link: '/vue/css/attr/text-emphasis-style.html' },
              { text: 'text-indent', link: '/vue/css/attr/text-indent.html' },
              { text: 'text-justify', link: '/vue/css/attr/text-justify.html' },
              { text: 'text-orientation', link: '/vue/css/attr/text-orientation.html' },
              { text: 'text-overflow', link: '/vue/css/attr/text-overflow.html' },
              { text: 'text-shadow', link: '/vue/css/attr/text-shadow.html' },
              { text: 'text-underline-position', link: '/vue/css/attr/text-underline-position.html' },
              { text: 'text-underline-offset', link: '/vue/css/attr/text-underline-offset.html' },
            ]
          },
          { text: 'top', link: '/vue/css/attr/top.html' },
          { text: 'transform', link: '/vue/css/attr/transform.html' },
          { text: 'transform-box', link: '/vue/css/attr/transform-box.html' },
          { text: 'transform-origin', link: '/vue/css/attr/transform-origin.html' },
          { text: 'transform-style', link: '/vue/css/attr/transform-style.html' },
          { text: 'transition', link: '/vue/css/attr/transition.html' },
          { text: 'transition-delay', link: '/vue/css/attr/transition-delay.html' },
          { text: 'transition-timing-function', link: '/vue/css/attr/transition-timing-function.html' },
          { text: 'translate 平移转换', link: '/vue/css/attr/translate.html' },
          { text: 'unicode-bidi 双向文本', link: '/vue/css/attr/unicode-bidi.html' },
          { text: 'vertical-align 垂直对齐', link: '/vue/css/attr/vertical-align.html' },
          { text: 'visibility', link: '/vue/css/attr/visibility.html' },
          { text: 'white-space', link: '/vue/css/attr/white-space.html' },
          { text: 'windows', link: '/vue/css/attr/windows.html' },
          { text: 'width', link: '/vue/css/attr/width.html' },
          { text: 'word-break', link: '/vue/css/attr/word-break.html' },
          { text: 'word-spacing', link: '/vue/css/attr/word-spacing.html' },
          { text: 'word-wrap', link: '/vue/css/attr/word-wrap.html' },
          { text: 'writing-mode', link: '/vue/css/attr/writing-mode.html' },
          { text: 'z-index', link: '/vue/css/attr/z-index.html' },
        ]
      },
      {
        text: 'CSS Pseudo-classes', collapsed: true, items: [
          { text: ':active', link: '/vue/css/pseudo-classes/active.html' },
          { text: ':checked', link: '/vue/css/pseudo-classes/checked.html' },
          { text: ':default', link: '/vue/css/pseudo-classes/default.html' },
          { text: ':disabled', link: '/vue/css/pseudo-classes/disabled.html' },
          { text: ':empty', link: '/vue/css/pseudo-classes/empty.html' },
          { text: ':enabled', link: '/vue/css/pseudo-classes/enabled.html' },
          { text: ':first-child', link: '/vue/css/pseudo-classes/first-child.html' },
          { text: ':first-of-type', link: '/vue/css/pseudo-classes/first-of-type.html' },
          { text: ':focus', link: '/vue/css/pseudo-classes/focus.html' },
          { text: ':fullscreen', link: '/vue/css/pseudo-classes/fullscreen.html' },
          { text: ':hover', link: '/vue/css/pseudo-classes/hover.html' },
          { text: ':in-range', link: '/vue/css/pseudo-classes/in-range.html' },
          { text: ':indeterminate', link: '/vue/css/pseudo-classes/indeterminate.html' },
          { text: ':invalid', link: '/vue/css/pseudo-classes/invalid.html' },
          { text: ':lang', link: '/vue/css/pseudo-classes/lang.html' },
          { text: ':last-child', link: '/vue/css/pseudo-classes/last-child.html' },
          { text: ':last-of-type', link: '/vue/css/pseudo-classes/last-of-type.html' },
          { text: ':link', link: '/vue/css/pseudo-classes/link.html' },
          { text: ':not', link: '/vue/css/pseudo-classes/not.html' },
          { text: ':nth-child', link: '/vue/css/pseudo-classes/nth-child.html' },
          { text: ':nth-last-child', link: '/vue/css/pseudo-classes/nth-last-child.html' },
          { text: ':nth-last-of-type', link: '/vue/css/pseudo-classes/nth-last-of-type.html' },
          { text: ':nth-of-type', link: '/vue/css/pseudo-classes/nth-of-type.html' },
          { text: ':only-child', link: '/vue/css/pseudo-classes/only-child.html' },
          { text: ':only-of-type', link: '/vue/css/pseudo-classes/only-of-type.html' },
          { text: ':optional', link: '/vue/css/pseudo-classes/optional.html' },
          { text: ':out-of-range', link: '/vue/css/pseudo-classes/out-of-range.html' },
          { text: ':read-only', link: '/vue/css/pseudo-classes/read-only.html' },
          { text: ':read-write', link: '/vue/css/pseudo-classes/read-write.html' },
          { text: ':required', link: '/vue/css/pseudo-classes/required.html' },
          { text: ':root', link: '/vue/css/pseudo-classes/root.html' },
          { text: ':target', link: '/vue/css/pseudo-classes/target.html' },
          { text: ':valid', link: '/vue/css/pseudo-classes/valid.html' },
          { text: ':visited', link: '/vue/css/pseudo-classes/visited.html' },
        ]
      },
      {
        text: 'CSS Pseudo-element', collapsed: true, items: [
          { text: '::after', link: '/vue/css/pseudo-element/after.html' },
          { text: '::before', link: '/vue/css/pseudo-element/before.html' },
          { text: '::first-letter', link: '/vue/css/pseudo-element/first-letter.html' },
          { text: '::first-line', link: '/vue/css/pseudo-element/first-line.html' },
          { text: '::placeholder', link: '/vue/css/pseudo-element/placeholder.html' },
          { text: '::selection', link: '/vue/css/pseudo-element/selection.html' },
        ]
      },
      {
        text: 'CSS 函数', collapsed: true, items: [
          { text: 'attr()', link: '/vue/css/function/attr.html' },
          { text: 'blur()', link: '/vue/css/function/blur.html' },
          { text: 'brightness()', link: '/vue/css/function/brightness.html' },
          { text: 'calc()', link: '/vue/css/function/calc.html' },
          { text: 'circle()', link: '/vue/css/function/circle.html' },
          { text: 'contrast()', link: '/vue/css/function/contrast.html' },
          { text: 'drop-shadow()', link: '/vue/css/function/drop-shadow.html' },
          { text: 'ellipse()', link: '/vue/css/function/ellipse.html' },
          { text: 'grayscale()', link: '/vue/css/function/grayscale.html' },
          { text: 'hsl()', link: '/vue/css/function/hsl.html' },
          { text: 'hsla()', link: '/vue/css/function/hsla.html' },
          { text: 'hue-rotate()', link: '/vue/css/function/hue-rotate.html' },
          { text: 'inset()', link: '/vue/css/function/inset.html' },
          { text: 'invert()', link: '/vue/css/function/invert.html' },
          { text: 'linear-gradient()', link: '/vue/css/function/linear-gradient.html' },
          { text: 'matrix()', link: '/vue/css/function/matrix.html' },
          { text: 'matrix3d()', link: '/vue/css/function/matrix3d.html' },
          { text: 'opacity()', link: '/vue/css/function/opacity.html' },
          { text: 'perspective()', link: '/vue/css/function/perspective.html' },
          { text: 'polygon()', link: '/vue/css/function/polygon.html' },
          { text: 'radial-gradient()', link: '/vue/css/function/radial-gradient.html' },
          { text: 'repeating-linear-gradient()', link: '/vue/css/function/repeating-linear-gradient.html' },
          { text: 'repeating-radial-gradient()', link: '/vue/css/function/repeating-radial-gradient.html' },
          { text: 'rgb()', link: '/vue/css/function/rgb.html' },
          { text: 'rgba()', link: '/vue/css/function/rgba.html' },
          { text: 'rotate()', link: '/vue/css/function/rotate.html' },
          { text: 'rotate3d()', link: '/vue/css/function/rotate3d.html' },
          { text: 'rotateX()', link: '/vue/css/function/rotateX.html' },
          { text: 'rotateY()', link: '/vue/css/function/rotateY.html' },
          { text: 'rotateZ()', link: '/vue/css/function/rotateZ.html' },
          { text: 'saturate()', link: '/vue/css/function/saturate.html' },
          { text: 'scale()', link: '/vue/css/function/scale.html' },
          { text: 'scale3d()', link: '/vue/css/function/scale3d.html' },
          { text: 'scaleX()', link: '/vue/css/function/scaleX.html' },
          { text: 'scaleY()', link: '/vue/css/function/scaleY.html' },
          { text: 'scaleZ()', link: '/vue/css/function/scaleZ.html' },
          { text: 'sepia()', link: '/vue/css/function/sepia.html' },
          { text: 'skew()', link: '/vue/css/function/skew.html' },
          { text: 'skewX()', link: '/vue/css/function/skewX.html' },
          { text: 'skewY()', link: '/vue/css/function/skewY.html' },
          { text: 'translate()', link: '/vue/css/function/translate.html' },
          { text: 'translate3d()', link: '/vue/css/function/translate3d.html' },
          { text: 'translateX()', link: '/vue/css/function/translateX.html' },
          { text: 'translateY()', link: '/vue/css/function/translateY.html' },
          { text: 'translateZ()', link: '/vue/css/function/translateZ.html' },
        ]
      },
      {
        text: 'CSS Layout', collapsed: true, items: [
        ]
      }
    ],
    "/vue/typescript/": [
      { text: '基础类型', link: '/vue/typescript/基础类型.html' },
      { text: '变量声明', link: '/vue/typescript/变量声明.html' },
      { text: '接口', link: '/vue/typescript/接口.html' },
      { text: '类', link: '/vue/typescript/类.html' },
      { text: '函数', link: '/vue/typescript/函数.html' },
      { text: '泛型', link: '/vue/typescript/泛型.html' },
      { text: '枚举', link: '/vue/typescript/枚举.html' },
      { text: '类型推断', link: '/vue/typescript/类型推断.html' },
      { text: '类型兼容性', link: '/vue/typescript/类型兼容性.html' },
      { text: '高级类型', link: '/vue/typescript/高级类型.html' },
      { text: '断言', link: '/vue/typescript/断言.html' },
      { text: 'symbols', link: '/vue/typescript/Symbols.html' },
      { text: '迭代器和生成器', link: '/vue/typescript/迭代器和生成器.html' },
      { text: '模块', link: '/vue/typescript/模块.html' },
      { text: '命名空间', link: '/vue/typescript/命名空间.html' },
      { text: '命名空间和模块', link: '/vue/typescript/命名空间和模块.html' },
      { text: '声明合并', link: '/vue/typescript/声明合并.html' },
      { text: 'JSX', link: '/vue/typescript/JSX.html' },
    ]
  },
}